### ISSUE TITLE
Database dump for AskYourGov

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/askyourgovug-theme#25]
When we move the AskYourGov site please can we take a database dump and send it to Michael as he wants to run some analysis on the data.

**Comment by garethrees** [comment]
https://wiki.mysociety.org/wiki/Sending_files_containing_sensitive_information

**Comment by garethrees** [comment]
https://groups.google.com/a/mysociety.org/d/msg/alaveteli/0IX9GOigYus/Eh33I-jtDAAJ

**Comment by garethrees** [comment]
Sent
